### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by qpc001** [zexinyang/GlobalMatch#1]
```
CMake Error at /usr/lib/cmake/vtk-6.3/vtkModuleAPI.cmake:120 (message):
  Requested modules not available:

    CommonCore
    CommonDataModel
Call Stack (most recent call first):
  /usr/lib/cmake/vtk-6.3/VTKConfig.cmake:80 (vtk_module_config)
  code/3rd_party/csf/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/udi/shared_dir/tools/GlobalMatch/build/CMakeFiles/CMakeOutput.log".
See also "/home/udi/shared_dir/tools/GlobalMatch/build/CMakeFiles/CMakeError.log".
```

I am using Ubuntu18.04 with system apt PCL-v1.8

**Comment by zexinyang** [comment]
Hey there! Thank you for your interest in our work.
I think the problem might be because we're using different versions of VTK (mine is 9.1). Could you try replacing the following lines with "find_package(VTK REQUIRED NO_MODULE)" and see if it fixes the issue? Thanks!I believe the issue may be due to the different version of VTK we are using. My version is 9.1. Could you please try replacing [this line](https://github.com/zexinyang/GlobalMatch/blob/4a1e965dfdada5bd48ca426d04b5269e1c5fd893/code/3rd_party/csf/CMakeLists.txt#L9) and [these lines](https://github.com/zexinyang/GlobalMatch/blob/4a1e965dfdada5bd48ca426d04b5269e1c5fd893/code/CMakeLists.txt#L9-L12) with `find_package(VTK REQUIRED NO_MODULE)` and see if it fixes the issue?

**Comment by zexinyang** [comment]
Hey there! Thank you for your interest in our work.

I think the problem might be because we're using different versions of VTK (mine is 9.1). Could you try replacing the following lines ([here](https://github.com/zexinyang/GlobalMatch/blob/4a1e965dfdada5bd48ca426d04b5269e1c5fd893/code/3rd_party/csf/CMakeLists.txt#L9) and [here](https://github.com/zexinyang/GlobalMatch/blob/4a1e965dfdada5bd48ca426d04b5269e1c5fd893/code/CMakeLists.txt#L9-L12)) with `find_package(VTK REQUIRED NO_MODULE)` and see if it fixes the issue?

**Comment by qpc001** [comment]
> I have updated the CMakeLists files and tested the code on several machines. The problem should now be resolved. Let me know if it doesn't work for you.

It works well. But I need to delete some lines of CMakeLists.txt
```
#target_compile_definitions(GlobalMatch PRIVATE
#        ${PCL_DEFINITIONS} # PCL definitions
#        )
```

Otherwise it will cause some error like this:
```
<command-line>:0:1: error: macro names must be identifiers
```
when exec `make -j8`

**Comment by zexinyang** [comment]
Awesome, you got it working! I tweaked the CMakeLists file based on your feedback, so hopefully it's all good now.
